### ISSUE TITLE
No module named 'PySide2.QtWebEngineWidgets (on r27397)

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#17]
```
During initialization the error "No module named 'PySide2.QtWebEngineWidgets'" occurred in /snap/freecad-ppd/146/usr/Mod/AddonManager/InitGui.py
Please look into the log file for further information
Unknown command 'Std_AddonMgr'
```

OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27397 (Git)
Build type: Release
Branch: master
Hash: e54b6e167a5d5ab863e8d4db68e4add65b1525ba
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by ppd** [comment]
https://github.com/ppd/freecad-ppd/actions/runs/1795324358

**Comment by ppd** [comment]
Seems to work. :)
