### ISSUE TITLE
Rogue UI artifact

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#18]
Start up freecad-ppd  
The rogue lines are visible on the startwb and subsequent windows

![image](https://user-images.githubusercontent.com/4140247/152656026-95b3d358-b94c-4036-9be4-8437a79e205c.png)

OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27402 (Git)
Build type: Release
Branch: master
Hash: 6b45122a46368cc2e11d34b8e5b6ff2b4560ded7
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

**Can't reproduce on AppImage**  
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by ppd** [comment]
I don't have those. Has it always been this way? Does stable have the same lines?

**Comment by luzpaz** [comment]
I just noticed it. Haven't checked stable yet.

**Comment by luzpaz** [comment]
Don't see it on 
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27432 (Git)
Build type: Release
Branch: master
Hash: 51d9ce64d02e4db71324cd0bf4ca2776d4d9af89
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

Weird. Closing ticket
