### ISSUE TITLE
FEM - No module named 'yaml'

### ISSUE THREAD

**Issue by tommirintala** [ppd/freecad-ppd#2]
When running FEM inside Freecad, the subjects error message appears.

I know the meaning of the error message. It means that the Freecad is unable to locate python's yaml -module. 

What I don't know, what is the correct way to add dependency to snap freacad. Since I have in local system python-yaml installed, but it is not used by snap instances.

**Comment by ppd** [comment]
I will add it and kick off a new build shortly. Thanks for the pointer.

**Comment by ppd** [comment]
Build for edge: https://github.com/ppd/freecad-ppd/actions/runs/1529726926
Build for stable: https://github.com/ppd/freecad-ppd/actions/runs/1529725293

The stable build will end up in candidate first. If you could refresh to that in about two hours and verify that it's working, I'd promote it to stable thereafter.

**Comment by tommirintala** [comment]
Wow -- this was fast!  I'll try it when it is available.  :partying_face:

**Comment by ppd** [comment]
```python
>>> import yaml
>>> yaml
<module 'yaml' from '/snap/freecad-ppd/72/usr/lib/python3/dist-packages/yaml/__init__.py'>
```

released revision 72 to stable

**Comment by tommirintala** [comment]
It took me longer to get back on desktop, than expected, sorry for the delay. And the tests, which I run, took a little longer, than I expected.

I tested both latest/edge and latest/candidate. In my tests, all relevant FEM functionality is now working, including the yaml and gmsh -- which could have been the next stopping point.

**Comment by ppd** [comment]
Excellent, thank you. Please file additional issues if you encounter any problems.
