### ISSUE TITLE
Implement weekly releases?

### ISSUE THREAD

**Issue by ppd** [ppd/freecad-ppd#22]
https://forum.freecadweb.org/viewtopic.php?p=573430#p573430

Maybe add a workflow for promoting revisions from edge to beta weekly.

@luzpaz Do you have an opinion on this?

**Comment by luzpaz** [comment]
Yea, if it's not an issue. why not? Shall we set it to once a week on Sunday like the AppImage ?

Edit: this may have changed (see https://github.com/FreeCAD/FreeCAD-Bundle/commit/78436503588e92fe3ae6c309e63ef3cae08e2dd8)

**Comment by ppd** [comment]
@kinghat This is now live. The workflow promotes edge -> beta every Sunday at 04:00.

**Comment by kinghat** [comment]
> @kinghat This is now live. The workflow promotes edge -> beta every Sunday at 04:00.

thanks for your time and effort on this :pray:

**Comment by ppd** [comment]
@kinghat I've promoted the revision containing this fix to beta.
