### ISSUE TITLE
'FreeCAD-Mechanical' snap able to accept drag-drop files in to FC while freecad-ppd (and conda) can't 

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#25]
Issue: https://forum.freecadweb.org/viewtopic.php?f=8&t=66615

This is the snap I'm referring to that doesn't show this bug: https://snapcraft.io/install/freecad-mechanical/arch

**Comment by ppd** [comment]
I have no such issues. I'm dragging a file from the desktop into the main window, and it shows up just fine.

**Comment by luzpaz** [comment]
:confused:

**Comment by luzpaz** [comment]
@ppd you can drag it in to an 'Open dialog' as well?

**Comment by ppd** [comment]
Which one do you use? The internal one or the portal one?

The internal one does nothing. But that's not really a snap-related thing, I'd say. Probably a regression.

**Comment by luzpaz** [comment]
This is the dialog that comes up when I press ctrl+o

![image](https://user-images.githubusercontent.com/4140247/155579166-124f7da3-d249-45b4-983a-c5530598df4b.png)

**Comment by ppd** [comment]
If you have a recent desktop portal, i.e. a recent distribution, you can switch to the portal file chooser. The other dialog does not support this. Drag &  drop to the main window works, however.

I guess you're seeing the portal file chooser in the freecad-mechanical snap.

**Comment by ppd** [comment]
@luzpaz I guess we can close this as this is just not implemented in the internal file chooser. For the record: This is not a snap-specific issue.
