### ISSUE TITLE
daily build failed `cp: cannot stat ../../xdg/qtchooser/default.conf': No such file or directory`

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#26]
https://github.com/ppd/freecad-ppd/runs/5685131918?check_suite_focus=true#step:4:4576

```
cp: cannot stat '/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current/etc/xdg/qtchooser/default.conf': No such file or directory
Failed to run 'override-build': Exit code was 1.
```

**Comment by ppd** [comment]
Yeah, the new snapcraft release uses an updated framework snap in the kde-neon extension: https://github.com/snapcore/snapcraft/commit/34578d30108f9c0b6e693a67a99786ae4b4d9848

A simple fix.

**Comment by luzpaz** [comment]
Nice!

**Comment by ppd** [comment]
https://github.com/ppd/freecad-ppd/actions/runs/2044235114

**Comment by ppd** [comment]
Runs fine. @realthunder will need the same.

**Comment by realthunder** [comment]
Thanks for the heads up.
