### ISSUE TITLE
Update to OCC 7.6.2

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#33]
https://dev.opencascade.org/content/open-cascade-technology-762-maintenance-release

**Comment by ppd** [comment]
https://github.com/ppd/freecad-deps-core20/commit/b9a45a0fbcd9cf5e768cefaee00faf032a4c5981
https://github.com/ppd/freecad-deps-core20/runs/6347515933?check_suite_focus=true

**Comment by ppd** [comment]
https://github.com/ppd/freecad-ppd/actions/runs/2292995249

**Comment by luzpaz** [comment]
Thank so much!
