### ISSUE TITLE
Snap for LinkStage3/LinkDaily

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#5]
Over at @realthunder's Assembly3 repo there are build instructions for building Assembly3 https://github.com/realthunder/FreeCAD_assembly3/wiki/Build-Instruction

I was wondering if we could have LS3 or LD Snap package as well ?

**Comment by ppd** [comment]
Yes, easily. We could create a snap `freecad-realthunder` or similar and essentially use the same recipes.

**Comment by ppd** [comment]
@luzpaz What kind of release scheme would you suggest? Nightly builds from `LinkDaily`+ current Assembly3 into `edge`? Does that make sense?

And `LinkStage3` would go into `stable`, just like the upstream releases do. Or does it make more sense to not install Assembly3 and leave that to the user?

Also, what package name do you think fits best? `freecad-realthunder`, `freecad-asm3` or something else?

**Comment by luzpaz** [comment]
Lets ask the author, @realthunder ? What do you prefer the snap package be called?

**Comment by realthunder** [comment]
>Nightly builds from `LinkDaily`+ current Assembly3 into `edge`? Does that make sense?
> 
> And `LinkStage3` would go into `stable`, just like the upstream releases do. Or does it make more sense to not install Assembly3 and leave that to the user?

`edge` and `stable` sounds fine. Thanks a lot. About `assembly3`, it needs to be bundled with `py_slvs` extension. I'd prefer to preinstall both if it won't cause any license issue, because you know, `slvs` is under GPL, while FreeCAD is LGPL.

**Comment by luzpaz** [comment]
@realthunder to avoid license issues ppd set it up so that `py_slvs` can be installed via `pip`

```markdown
  There are multiple apps/commands included in the snap:
  
  - `freecad-ppd.freecad`:  Run FreeCAD
  - `freecad-ppd.cmd`:      Run FreeCAD command line interface
  - `freecad-ppd.pip`:      Install python packages for user (not system-wide). E.g.
  `freecad-ppd.pip install py_slvs` for Assembly3.
```
-from `snap info freecad-ppd`

**Comment by realthunder** [comment]
That's great

**Comment by ppd** [comment]
@realthunder Do your appimages contain py_slvs? The same licence issues would apply here, too.

**Comment by realthunder** [comment]
Yes, indeed. I probably should do the same. Do you know any similar way to pip install for some specific appimage?

**Comment by ppd** [comment]
@realthunder You can ship pip inside the appimage and just call it with `--target` to some suitable directory. Or set the `PIP_TARGET` env variable. Then, launch FreeCAD with an additional `-p` to add this directory as a python path. I do something a little more hack-like and install to a directory in `Mod` because FreeCAD loads all those by default, and I didn't have to ship a launcher script.

see

```yaml
environment:
[...]
  FREECAD_USER_HOME: $SNAP_USER_COMMON
[...]
  PIP_TARGET: $SNAP_USER_COMMON/Mod/snap-user-packages
```

@luzpaz It's possible to add a UI to make installing py_slvs a little more accessible to the average user.

**Comment by realthunder** [comment]
I'll try that out. Thanks!

**Comment by luzpaz** [comment]
@ppd A UI was would be awesome and I think users would appreciate that more since it's their choice to make.

**Comment by ppd** [comment]
@realthunder It's also possible to integrate the packaging with your repo directly. Would you be interested in that? Building on each push etc. would also be possible then.

We could set up a package `freecad-realthunder` and add you, @luzpaz and me as collaborators for maintaining it (there's not much to do except adding a bit of description).

**Comment by realthunder** [comment]
That'll be great. Do I need to do anything on my side?

**Comment by ppd** [comment]
I'll create a PR and include the relevant technical details there. Aside from that, you should create a developer account at https://snapcraft.io/, e.g. "realthunder", and also register a snap name, e.g. "freecad-realthunder".

**Comment by realthunder** [comment]
> you should create a developer account at https://snapcraft.io/, e.g. "realthunder", and also register a snap name, e.g. "freecad-realthunder".

Done.

**Comment by luzpaz** [comment]
Just checking in on where we're at with the realthunder snap (+ edge) ?

**Comment by ppd** [comment]
I'm on it. PR maybe (hopefully) tomorrow.

**Comment by ppd** [comment]
@luzpaz Current draft is here: https://github.com/ppd/FreeCAD/tree/realthunder-snap

It's mostly a straight port of this recipe + Assembly3 (currently just HEAD) + an install prompt that calls pip for you to install py_slvs.

**Comment by luzpaz** [comment]
@ppd how do I install it?

**Comment by ppd** [comment]
At the moment, nothing's been published. Because this issue does not really belong to freecad-ppd, and a PR has been created (and is in the finishing stages), I've decided to close this issue.

**Comment by luzpaz** [comment]
@ppd understood but where can I keep an eye out to know when the snap goes live?

**Comment by ppd** [comment]
It will be built via GitHub actions in realthunder's FreeCAD repo. So just wait for the PR to be merged there (very soon).

**Comment by ppd** [comment]
@luzpaz The PR in realthunder's repo is now ready. The improvements from there will be included in this repo here also.
If you want to test and have a reasonably fast computer, you can build it yourself (see PR) to try it out.

**Comment by luzpaz** [comment]
Thanks. I don't have a reasonably fast computer, lol. But I may try it anyway!

**Comment by ppd** [comment]
Well, I could probably upload a revision on Dropbox and send you a link till realthunder gets his own builds going.
