### ISSUE TITLE
Offtopic: Could you make and 'edge' for Scribus ?

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#6]
Sorry to off-topic post this here. But I was wondering if you'd be interested in creating a snap for Scribus edge ?
https://gitlab.com/scribus/scribus

**Comment by ppd** [comment]
I haven't used Scribus in many years, so I'd be a bad candidate to create a snap for it. My CAD snaps (solvespace, FreeCAD, QElectroTech...) were first created while I still had a job that made use of them in some ways. Otherwise, I'd most likely not have started working on them.
