### ISSUE TITLE
Question: snapd doesn't tell me that it's updating freecad-ppd edge in the background. How can i make it?

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#7]
Been enjoying freecad-ppd edge but am mystified by how it stays updated in the background without telling me. I tried searching for an answer but did find one. Can you share with me what I need to know? Is there a way for my system to show me what is usually kept silent and in the background?

**Comment by ppd** [comment]
You can enable refresh awareness: https://snapcraft.io/blog/experimental-feature-snap-refresh-awareness-and-update-inhibition
so:  `snap set core experimental.refresh-app-awareness=true`

It should refrain from updating the snap while you're using it.
