### ISSUE TITLE
Problem with main menu

### ISSUE THREAD

**Issue by marekmarecki** [ppd/freecad-ppd#9]
Hello,
I just encountered your snap and gave it a go since official snap is on some old revision. But I have a question about main menu - it works on 'freecad' snap, but on 'freecad-ppd' is not (my DE is Unity and I am on Ubuntu 20.04). Do you have idea why that would be?
'freecad stable':
![freecad-stable](https://user-images.githubusercontent.com/776138/148686557-f3e74d9a-0c4c-40a3-91f8-e5cd83e0b0a4.png)
'freecad-ppd stable'
![freecad-ppd-stable](https://user-images.githubusercontent.com/776138/148686565-549d12df-a3a9-496f-9467-ce8f219f5cd4.png)

**Comment by ppd** [comment]
This is most likely a missing `unity7` plug. I'll add it.

**Comment by ppd** [comment]
The stable build: https://github.com/ppd/freecad-ppd/actions/runs/1674185553
The edge build: https://github.com/ppd/freecad-ppd/actions/runs/1674186096

Should be ready in ~2 hours. You can then try it from the candidate channel.

**Comment by ppd** [comment]
@marekmarecki Please report back if the current revision in candidate works for you. Thanks.

**Comment by marekmarecki** [comment]
I'm glad to report that your guess was right:

![freecad-ppd-candidate](https://user-images.githubusercontent.com/776138/148695583-042becb6-f764-4860-8ac5-f73fe067210b.png)

Thanks for the super fast fix! :+1:

**Comment by ppd** [comment]
I'll release it to stable then. Thanks for the report and the testing.
